# Generated by Django 4.0.6 on 2023-03-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyInsert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastnane', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('modelname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users1',
            },
        ),
        migrations.CreateModel(
            name='SellInsert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('ModelName', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=255)),
                ('Year', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
