# Generated by Django 4.0.6 on 2023-03-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_buyinsert_sellinsert'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buyinsert',
            table='ds',
        ),
    ]
