# Generated by Django 4.0.6 on 2023-03-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_alter_buyinsert_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buyinsert',
            table=None,
        ),
    ]
