# Generated by Django 4.0.6 on 2023-03-19 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_alter_buyinsert_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buyinsert',
            table='ds',
        ),
    ]
