# Generated by Django 4.0.6 on 2023-03-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0005_alter_buyinsert_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('modelname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ds',
            },
        ),
        migrations.DeleteModel(
            name='BuyInsert',
        ),
    ]
