# Generated by Django 4.0.6 on 2023-03-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0006_buy_delete_buyinsert'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buy',
            table=None,
        ),
    ]
