# Generated by Django 4.0.6 on 2023-03-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0007_alter_buy_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buy',
            table='ds',
        ),
    ]
